### ISSUE TITLE
无法搜索

### ISSUE THREAD

**Issue by lifujie25** [fengymi/emby-plugin-danmu#1]
无法搜索和自动下载弹幕

**Comment by fengymi** [comment]
> 无法搜索和自动下载弹幕

是不支持搜索的，目前只能在任务里面操作

**Comment by fengymi** [comment]
> 新增的媒体库,会自动下载是吧

现在不会没加，通过定时下载

**Comment by fengymi** [comment]
着急的话可以通过api手动执行

**Comment by lifujie25** [comment]
期待后续完整效果,embt很多人用,刚在群里说了一下,一堆人有兴趣
