### ISSUE TITLE
重新扫描媒体库文件问题

### ISSUE THREAD

**Issue by xxzj990** [fengymi/emby-plugin-danmu#10]
手动点击媒体库菜单中的“扫描媒体库文件”，会触发所有文件的字幕的下载。

有没有可能手动点击“扫描媒体库文件”时不去触发字幕下载，只在手动搜索字幕或者新增媒体文件时触发字幕下载。

原因是媒体库比较大，文件非常多，如果触发字幕下载，下载一段时间后会导致emby崩溃。

**Comment by fengymi** [comment]
> 手动点击媒体库菜单中的“扫描媒体库文件”，会触发所有文件的字幕的下载。
> 
> 有没有可能手动点击“扫描媒体库文件”时不去触发字幕下载，只在手动搜索字幕或者新增媒体文件时触发字幕下载。
> 
> 原因是媒体库比较大，文件非常多，如果触发字幕下载，下载一段时间后会导致emby崩溃。

你先临时把 弹幕字幕插件不勾选，刷新完再加上。 这个功能我看看咋支持

**Comment by xxzj990** [comment]
> > 手动点击媒体库菜单中的“扫描媒体库文件”，会触发所有文件的字幕的下载。
> > 有没有可能手动点击“扫描媒体库文件”时不去触发字幕下载，只在手动搜索字幕或者新增媒体文件时触发字幕下载。
> > 原因是媒体库比较大，文件非常多，如果触发字幕下载，下载一段时间后会导致emby崩溃。
> 
> 你先临时把 弹幕字幕插件不勾选，刷新完再加上。 这个功能我看看咋支持

好的，我试试。

如果emby支持这样做，是不是可以加个开关。

**Comment by fengymi** [comment]
> > > 手动点击媒体库菜单中的“扫描媒体库文件”，会触发所有文件的字幕的下载。
> > > 有没有可能手动点击“扫描媒体库文件”时不去触发字幕下载，只在手动搜索字幕或者新增媒体文件时触发字幕下载。
> > > 原因是媒体库比较大，文件非常多，如果触发字幕下载，下载一段时间后会导致emby崩溃。
> > 
> > 
> > 你先临时把 弹幕字幕插件不勾选，刷新完再加上。 这个功能我看看咋支持
> 
> 好的，我试试。
> 
> 如果emby支持这样做，是不是可以加个开关。

嗯，可以。得看看能不能识别出是手动还是，新增
