### ISSUE TITLE
大佬，emby怎么读取xml文件，我的不会自动加载弹幕啊

### ISSUE THREAD

**Issue by 911201wjj** [fengymi/emby-plugin-danmu#11]

**Comment by fengymi** [comment]
哪个app

**Comment by 911201wjj** [comment]
> 哪个app

Emby网页端,找不到弹幕开关选项

**Comment by fengymi** [comment]
> > 哪个app
> 
> Emby网页端,找不到弹幕开关选项

网页版只能用字幕形式挂载

**Comment by 911201wjj** [comment]
> 挂载

那应该用什么客户端才能读取

**Comment by 911201wjj** [comment]
> > > 哪个app
> 
> > 
> 
> > Emby网页端,找不到弹幕开关选项
> 
> 
> 
> 网页版只能用字幕形式挂载

那要用什么客户端，我用了Fileball也无法读取到弹幕，大佬是什么原因呢

**Comment by fengymi** [comment]
> > > > 哪个app
> > 
> > 
> > > 
> > 
> > 
> > > Emby网页端,找不到弹幕开关选项
> > 
> > 
> > 网页版只能用字幕形式挂载
> 
> 那要用什么客户端，我用了Fileball也无法读取到弹幕，大佬是什么原因呢

看看jellyfin版
https://github.com/cxfksword/jellyfin-plugin-danmu
我没用过解析xml的

**Comment by moetayuko** [comment]
我用 switchfin 读不到 xml 弹幕，[查看代码发现](https://github.com/dragonflylee/switchfin/blob/e5f519523e9362b42e5ef045cd5fd34d66c02a60/app/include/api/jellyfin/media.hpp#L31)他是用 `/api/danmu/{id}/raw` 来获取的，但本插件没有实现该接口（jellyfin 版本实现了）

**Comment by fengymi** [comment]
> 我用 switchfin 读不到 xml 弹幕，[查看代码发现](https://github.com/dragonflylee/switchfin/blob/e5f519523e9362b42e5ef045cd5fd34d66c02a60/app/include/api/jellyfin/media.hpp#L31)他是用 `/api/danmu/{id}/raw` 来获取的，但本插件没有实现该接口（jellyfin 版本实现了）

对文件名有要求吗，我可以加下

**Comment by moetayuko** [comment]
> > 我用 switchfin 读不到 xml 弹幕，[查看代码发现](https://github.com/dragonflylee/switchfin/blob/e5f519523e9362b42e5ef045cd5fd34d66c02a60/app/include/api/jellyfin/media.hpp#L31)他是用 `/api/danmu/{id}/raw` 来获取的，但本插件没有实现该接口（jellyfin 版本实现了）
> 
> 对文件名有要求吗，我可以加下

似乎没有 https://github.com/cxfksword/jellyfin-plugin-danmu/blob/71f8838d5c234f6740b28c88b5fd40146ec2c292/Jellyfin.Plugin.Danmu/Controllers/DanmuController.cs#L88

**Comment by fengymi** [comment]
> > > 我用 switchfin 读不到 xml 弹幕，[查看代码发现](https://github.com/dragonflylee/switchfin/blob/e5f519523e9362b42e5ef045cd5fd34d66c02a60/app/include/api/jellyfin/media.hpp#L31)他是用 `/api/danmu/{id}/raw` 来获取的，但本插件没有实现该接口（jellyfin 版本实现了）
> > 
> > 
> > 对文件名有要求吗，我可以加下
> 
> 似乎没有 https://github.com/cxfksword/jellyfin-plugin-danmu/blob/71f8838d5c234f6740b28c88b5fd40146ec2c292/Jellyfin.Plugin.Danmu/Controllers/DanmuController.cs#L88

https://github.com/fengymi/emby-plugin-danmu/issues/11#issuecomment-2308059349

用这个版本试试，和jellyfin有点不一样，没有File的类，直接返回byte流，不知道会不会有问题

**Comment by moetayuko** [comment]
> > > > 我用 switchfin 读不到 xml 弹幕，[查看代码发现](https://github.com/dragonflylee/switchfin/blob/e5f519523e9362b42e5ef045cd5fd34d66c02a60/app/include/api/jellyfin/media.hpp#L31)他是用 `/api/danmu/{id}/raw` 来获取的，但本插件没有实现该接口（jellyfin 版本实现了）
> > > 
> > > 
> > > 对文件名有要求吗，我可以加下
> > 
> > 
> > 似乎没有 https://github.com/cxfksword/jellyfin-plugin-danmu/blob/71f8838d5c234f6740b28c88b5fd40146ec2c292/Jellyfin.Plugin.Danmu/Controllers/DanmuController.cs#L88
> 
> [#11 (comment)](https://github.com/fengymi/emby-plugin-danmu/issues/11#issuecomment-2308059349)
> 
> 用这个版本试试，和jellyfin有点不一样，没有File的类，直接返回byte流，不知道会不会有问题

1.0.1.1 不行，switchfin 报错 `[ERROR] Error decode danmaku xml[1]: 13` https://github.com/dragonflylee/switchfin/blob/e5f519523e9362b42e5ef045cd5fd34d66c02a60/app/src/activity/player_view.cpp#L325

我本地用 curl 构造请求返回是空（不确定这样请求对不对）
```
❯ curl -H 'X-Emby-Token: b0b8bcd7af46410b83b7dd39312d4816' http://192.168.5.2:8096/api/danmu/559807/raw -v
*   Trying 192.168.5.2:8096...
* Connected to 192.168.5.2 (192.168.5.2) port 8096
> GET /api/danmu/559807/raw HTTP/1.1
> Host: 192.168.5.2:8096
> User-Agent: curl/8.9.1
> Accept: */*
> X-Emby-Token: b0b8bcd7af46410b83b7dd39312d4816
> 
* Request completely sent off
< HTTP/1.1 204 No Content
< Content-Length: 0
< Date: Sat, 24 Aug 2024 05:07:20 GMT
< Server: UPnP/1.0 DLNADOC/1.50
< Access-Control-Allow-Headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Token, X-Emby-Client, X-Emby-Client-Version, X-Emby-Device-Id, X-Emby-Device-Name, X-Emby-Authorization
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
< Access-Control-Allow-Origin: *
< Cross-Origin-Resource-Policy: cross-origin
< Access-Control-Allow-Private-Network: true
< Private-Network-Access-Name: synology
< Private-Network-Access-Id: 5060ffae01a848d19bd791d8a5af2cac
< 
* Connection #0 to host 192.168.5.2 left intact
```

**Comment by fengymi** [comment]
奇怪，我本地用curl是可以的
你用浏览器打开看看，http://192.168.5.2:8096/api/danmu/559807/raw?X-Emby-Token=b0b8bcd7af46410b83b7dd39312d4816
![image](https://github.com/user-attachments/assets/515531d6-7974-4922-8ba6-74c5c81c842f)

**Comment by moetayuko** [comment]
没问题了，我刚刚测的那集恰好没弹幕。。。
