### ISSUE TITLE
请求更新TV2.1.21g版客户端

### ISSUE THREAD

**Issue by naoki66** [fengymi/emby-plugin-danmu#14]
![IMG_20240823_204036.jpg](https://github.com/user-attachments/assets/1c1129de-6768-4434-b290-b1ee886dd1c8)

商店已经更新到2.1.21g版了，请求更新。多谢。

**Comment by naoki66** [comment]
![Screenshot_2024-08-24-01-47-03-657_com.android.vending-edit.jpg](https://github.com/user-attachments/assets/1fd1267a-0fc0-4e2c-b232-bf31ff5f3490)

**Comment by fengymi** [comment]
你这个哪个商店的，我看github上还是2个月之前的
https://github.com/MediaBrowser/Emby.Releases/tree/master

**Comment by naoki66** [comment]
谷歌商店，已经更新了。

**Comment by fengymi** [comment]
我下了个版本看了下还是2.14，你发个2.1.21的看看

**Comment by naoki66** [comment]
https://play.google.com/store/apps/details?id=tv.emby.embyatv
测试版2024.8.17更新已经是2.1.21g

**Comment by naoki66** [comment]
![Screenshot_2024-09-16-09-18-51-087_com.android.vending-edit.jpg](https://github.com/user-attachments/assets/41fb2e04-3bca-433d-8cef-76077c9cc105)

能否把tv版的倍速播放也放到第一界面菜单旁边呢？比如弹幕选项旁边，目前需要到最右边的-设置-倍速播放-选择速率。操作太复杂了。

**Comment by cdlongbow** [comment]
请求更新embyTV 2.1.21g版客户端，你的倍速记忆播放功能真的太好用了，奉上破解版https://yoyodadada.lanzouw.com/i48lk2a1z0aj，谢谢！

**Comment by naoki66** [comment]
> 请求更新embyTV 2.1.21g版客户端，你的倍速记忆播放功能真的太好用了，谢谢！奉上破解版https://yoyodadada.lanzouw.com/i48lk2a1z0aj

非常感谢！  哪里可以看到这位大佬的更新呢？   这个支持danmu吗？

**Comment by naoki66** [comment]
> > > 请求更新embyTV 2.1.21g版客户端，你的倍速记忆播放功能真的太好用了，谢谢！奉上破解版https://yoyodadada.lanzouw.com/i48lk2a1z0aj
> > 
> > 
> > 非常感谢！ 哪里可以看到这位大佬的更新呢？ 这个支持danmu吗？
> 
> 没有，就是请老大做呀，同时把倍速记忆播放功能带上。

官方的安卓TV版本，当播放DTS-HD and TrueHD时，倍速播放选项被隐藏。标准版的安卓版本，当播放DTS-HD and TrueHD时，倍速播放选项没有被隐藏，但是选择无效，会自动切换回1x速度。
去官方论坛反馈， 说是要在选中把音频混到立体声。但是我目前没找到选项。

**Comment by fengymi** [comment]
> > > 请求更新embyTV 2.1.21g版客户端，你的倍速记忆播放功能真的太好用了，谢谢！奉上破解版https://yoyodadada.lanzouw.com/i48lk2a1z0aj
> > 
> > 
> > 非常感谢！ 哪里可以看到这位大佬的更新呢？ 这个支持danmu吗？
> 
> 没有，就是请老大做呀，同时把倍速记忆播放功能带上。

有测试服务器和账号吗，我现在没有服务器地址，我验证下

**Comment by naoki66** [comment]
怎么样才可以私密的提供给大佬？

**Comment by fengymi** [comment]
> 怎么样才可以私密的提供给大佬？

不用了，我搞完了。我发一版吧

**Comment by naoki66** [comment]
请求更新到2.1.23 （2024年12 月 7 日）

https://emby.media/community/index.php?/topic/42240-emby-android-tv-release-notes-beta/
