### ISSUE TITLE
提示“获取弹幕异常，进行第N次重试“

### ISSUE THREAD

**Issue by Grylag** [fengymi/emby-plugin-danmu#15]
用的是主页发布的tv端
![Uploading QQ图片20240823223426.jpg…]()

**Comment by fengymi** [comment]
看看服务端日志，插件装了吗

**Comment by Grylag** [comment]
插件装上了，日志要取哪部分呢？
![01](https://github.com/user-attachments/assets/9e7f7d3f-0384-4053-854d-dd5466b36a20)

**Comment by fengymi** [comment]
看看日志有什么报错

**Comment by Grylag** [comment]
![01](https://github.com/user-attachments/assets/f2a5746f-8023-4282-876d-ba7159ef36cb)
![02](https://github.com/user-attachments/assets/d24eae7d-00aa-4940-afef-b83e69373c9a)
![03](https://github.com/user-attachments/assets/a7739c45-5d9f-4498-8d49-4e855296d77b)
[embyserver.txt](https://github.com/user-attachments/files/16735039/embyserver.txt)
看看能不能查到，或者还需要什么信息

**Comment by fengymi** [comment]
弹幕刮削好了吗，可以浏览器手动打开看看能不能获取弹幕
/api/danmu/${媒体id}?option=GetJsonById&X-Emby-Token={token}

**Comment by fengymi** [comment]
文件是挂载在远程的吗，我看读取文件的时候怎么是走的ip

**Comment by Grylag** [comment]
![01](https://github.com/user-attachments/assets/ef698ba0-f941-4744-bfde-bbfa0024ee5c)
![02](https://github.com/user-attachments/assets/c768e723-e1cb-406c-9988-0f2066a9a325)
![03](https://github.com/user-attachments/assets/3339b9f3-29d4-45ab-9497-3fe43ad4f8c0)
勾选了生成ASS，但文件夹没有；挂的SMB

**Comment by fengymi** [comment]
你这个看起来文件就没写入成功，你刮削的文件是不是在smb原机器上刮的

**Comment by Grylag** [comment]
有一些是以前TMM刮削的，后面挂了emby之后就用emby刮了

**Comment by fengymi** [comment]
> 有一些是以前TMM刮削的，后面挂了emby之后就用emby刮了

你手动刮削一个弹幕试试，看看能不能保存到目录

**Comment by Grylag** [comment]
试了刮削没存到，搜字幕也没搜到有

**Comment by fengymi** [comment]
> 试了刮削没存到，搜字幕也没搜到有

看看有没有报错，可能就是没有弹幕

**Comment by Grylag** [comment]
不知道是不是媒体库设置问题，但我看图片和nfo都没写入媒体文件夹，估计是在服务器元数据文件夹里；试了手动修改字幕搜索不到，拉了操作时间对应的日志，麻烦帮忙看看咯
![02](https://github.com/user-attachments/assets/d1ae3f97-ffde-440b-b3ff-4da88fc6ff34)
![03](https://github.com/user-attachments/assets/0efa6adf-8353-4ee4-8b66-7ab3f71c5ba6)
![01](https://github.com/user-attachments/assets/effaac48-77d9-4ab5-a1c5-5a342d4eb300)
[log.txt](https://github.com/user-attachments/files/16736701/log.txt)

**Comment by fengymi** [comment]
> 但我看图片和nfo都没写入媒体文件夹，估计是在服务器元数据文件夹里；试了手动修改字幕搜索不到，拉了操作时间对应的日志，麻烦帮忙看看咯

上机器手动执行curl查询弹幕，然后创建文件保存试试。
