### ISSUE TITLE
问下大佬，pc端有办法支持吗

### ISSUE THREAD

**Issue by DaiDai-X** [fengymi/emby-plugin-danmu#16]
win的pc端，客户端或者网页端（通过油猴）都行
谢谢了

**Comment by fengymi** [comment]
自己没需求，懒得搞。你可以自己搞搞js，可以支持web端

**Comment by naoki66** [comment]
> 自己没需求，转jellyfin了，最近在改jellyfin tv端。你可以自己搞搞js，可以支持web端

请教https://github.com/fengymi/jellyfin-androidtv 这个没有发布Releases，能否更新一个带danmu的版本呢？
https://github.com/jellyfin/jellyfin-androidtv/releases
目前是[v0.17.5](https://github.com/jellyfin/jellyfin-androidtv/releases/tag/v0.17.5)

**Comment by fengymi** [comment]
> > 自己没需求，转jellyfin了，最近在改jellyfin tv端。你可以自己搞搞js，可以支持web端
> 
> 请教https://github.com/fengymi/jellyfin-androidtv 这个没有发布Releases，能否更新一个带danmu的版本呢？ https://github.com/jellyfin/jellyfin-androidtv/releases 目前是[v0.17.5](https://github.com/jellyfin/jellyfin-androidtv/releases/tag/v0.17.5)

https://github.com/fengymi/jellyfin-androidtv/releases/tag/v0.0.0-beta
弹幕基础功能有了，我先临时打个版本给你用下

**Comment by fengymi** [comment]
> win的pc端，客户端或者网页端（通过油猴）都行 谢谢了

可以看看他们使用的
https://github.com/fengymi/emby-plugin-danmu/issues/11
