### ISSUE TITLE
我使用开心版的emby上传插件后后台没有显示

### ISSUE THREAD

**Issue by xnibnx** [fengymi/emby-plugin-danmu#17]
我是软路由系统，在上传插件后不能显示。docker emby破解版是版本 [4.8.0.42] 测试版。

**Comment by fengymi** [comment]
> 我是软路由系统，在上传插件后不能显示。docker emby破解版是版本 [4.8.0.42] 测试版。

更新下，用4.8.8

**Comment by xnibnx** [comment]
大家帮忙点击下网址谢谢：360主页

**Comment by xnibnx** [comment]
大家帮忙点击下网址谢谢：360主页
