### ISSUE TITLE
emby只能安装apk使用弹幕吗 网页上好像不行，没看到弹幕相关配置

### ISSUE THREAD

**Issue by 1647561692** [fengymi/emby-plugin-danmu#19]

**Comment by free-150** [comment]
网页上是加载字幕的方式

**Comment by 1647561692** [comment]
> 网页上是加载字幕的方式
这个是说，在字幕那有配置的地方吗，还是会变成一个字幕自己去选，还是随字幕自动加载

**Comment by fengymi** [comment]
> > 网页上是加载字幕的方式
> > 这个是说，在字幕那有配置的地方吗，还是会变成一个字幕自己去选，还是随字幕自动加载

后台下载弹幕保存为字幕，然后字幕是各地方通用

**Comment by free-150** [comment]
变成danmu.ass文件，选择后会加载弹幕。如果视频本身有字幕就只要加载这个danmu字幕即可，如果本身没有字幕想要加载字幕的同时又要加载弹幕就得用支持双字幕或xml文件的客户端。
这种方式有优点：
- 优点是相对于内置云弹幕的方式来说它基本不需要改客户端，这对ios签名难很友好。
- 还有就是弹幕可以全网爬取自行添加，云弹幕的方式不能自由选择弹幕源。
缺点也是有的，自行体会

**Comment by 1647561692** [comment]
ok

**Comment by HASS-yang** [comment]
> 变成danmu.ass文件，选择后会加载弹幕。如果视频本身有字幕就只要加载这个danmu字幕即可，如果本身没有字幕想要加载字幕的同时又要加载弹幕就得用支持双字幕或xml文件的客户端。 这种方式有优点：
> 
> * 优点是相对于内置云弹幕的方式来说它基本不需要改客户端，这对ios签名难很友好。
> * 还有就是弹幕可以全网爬取自行添加，云弹幕的方式不能自由选择弹幕源。
>   缺点也是有的，自行体会

请问安卓有没有双字幕或者XML文件的软件，试了弹弹PLAY但是只能通过文件共享的方式，不能使用媒体库模式
