### ISSUE TITLE
请问如何在群晖docker环境下安装这个插件

### ISSUE THREAD

**Issue by gothicry** [fengymi/emby-plugin-danmu#20]
大佬你好 我尝试了创建plugins目录 然后docker的emby内把plugins文件夹挂载成/system/plugins  并把插件文件丢进去 安装不上  然后也尝试了进入了容器内部 把插件文件用cp命令复制进容器内部的plugins文件夹  也是安装不上 请问应该如何操作才能安装上呢

**Comment by gothicry** [comment]
补充：emby版本为4.7.14.0使用docker安装    dsm7.2.1

**Comment by fengymi** [comment]
插件安装方法和其他插件没有任何区别，但是这种兼容性问题需要你自己排查，看看日志啥的
当时适用的版本是4.8.8.0，其他版本没试过

**Comment by Edwinzzzs2** [comment]
群晖这个我也试过，貌似docker版本总是加载不上，但是用套件版可以，我就放弃了docker版本，直接套件了，可以用这个插件
