### ISSUE TITLE
希望加入本地弹幕加载功能

### ISSUE THREAD

**Issue by TtbqSora** [fengymi/emby-plugin-danmu#21]
希望可以自动加载本地文件夹内已经下载好的和视频同名xml弹幕文件

**Comment by fengymi** [comment]
> 希望可以自动加载本地文件夹内已经下载好的和视频同名xml弹幕文件

什么意思，什么场景。

**Comment by TtbqSora** [comment]
![QQ截图20241126213526](https://github.com/user-attachments/assets/6d8d0dff-4c34-4dc2-a074-4ebc04f7e3ca)
就是本地已经在B站下载好了xml弹幕文件，和视频同名，希望可以直接加载本地已有的

**Comment by fengymi** [comment]
你说tv端app吗
