### ISSUE TITLE
貌似字幕与弹幕无法同时显示？

### ISSUE THREAD

**Issue by Geneww** [fengymi/emby-plugin-danmu#3]
<img width="1543" alt="image" src="https://github.com/user-attachments/assets/d48d52c0-2f1a-4670-9b36-1a59e9fa476d">

**Comment by fengymi** [comment]
> 这里选择对应字幕后，上方弹幕不显示了。

是的，这个字幕版是这样的，如果是tv端可以用我这个app，是支持的。其他的话需要播放器支持多个字幕，或者支持xml文件
