### ISSUE TITLE
出现相同key错误

### ISSUE THREAD

**Issue by edhnt455** [fengymi/emby-plugin-danmu#5]
我用的amilys/emby镜像，把Emby.Plugin.Danmu文件放到/config/plugins文件夹内，插件设置是这样的。
![image](https://github.com/user-attachments/assets/f8bb1852-9592-4ec1-ae81-2cb48686c4a6)
手动执行计划任务后报错，日志:
An item with the same key has already been added. Key: DandanID at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value) at Emby.Plugin.Danmu.ScheduledTasks.AbstractDanmuTask.GetScraperFilter(ReadOnlyCollection`1 scrapers) at Emby.Plugin.Danmu.ScheduledTasks.RefreshDanmuTask.Execute(CancellationToken cancellationToken, IProgress`1 progress) at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)

**Comment by fengymi** [comment]
知道怎么操作出现的吗，你看看plugins/configurations/Emby.Plugin.Danmu.xml 是不是有重复的，先删除重复的临时解决下。这个问题我看看能不能复现

**Comment by fengymi** [comment]
https://github.com/fengymi/emby-plugin-danmu/releases/tag/1.0.1

**Comment by edhnt455** [comment]
用了最新的已经可以正常运行啦，感谢作者大大😀
