### ISSUE TITLE
emby 4.8.0.21没生效

### ISSUE THREAD

**Issue by sunxianhong** [fengymi/emby-plugin-danmu#7]
大佬这个适用于什么版本emby

**Comment by sunxianhong** [comment]
![1722393320593](https://github.com/user-attachments/assets/4169c9c6-b228-4c5c-af03-d67b6d34b34d)

**Comment by fengymi** [comment]
我现在用的是[4.8.8.0] ， 有启动报错日志吗

**Comment by sunxianhong** [comment]
> 我现在用的是[4.8.8.0] ， 有启动报错日志吗

我试了几个版本好像低于4.8.8的都不行，现在下了4.8.8可以了，测试了两个优酷的剧好像下不到字幕，白夜追凶和度年华，其他两个站可以，大佬太牛了

**Comment by sunxianhong** [comment]
> 我现在用的是[4.8.8.0] ， 有启动报错日志吗

![Screenshot_20240731_185437.jpg](https://github.com/user-attachments/assets/768f3c2b-83d3-4a0a-9d19-63fe51c1eba0)

我之前用的是这个版本，这个版本可以解锁硬解但是不支持这个插件要是能适配太好了，正版有点望尘莫及

**Comment by fengymi** [comment]
> > 我现在用的是[4.8.8.0] ， 有启动报错日志吗
> 
> 我试了几个版本好像低于4.8.8的都不行，现在下了4.8.8可以了，测试了两个优酷的剧好像下不到字幕，白夜追凶和度年华，其他两个站可以，大佬太牛了

这个两个优酷有吗，可以看看日志有没有什么提示

**Comment by fengymi** [comment]
> > 我现在用的是[4.8.8.0] ， 有启动报错日志吗
> 
> ![Screenshot_20240731_185437.jpg](https://private-user-images.githubusercontent.com/57023545/353803648-768f3c2b-83d3-4a0a-9d19-63fe51c1eba0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjkwNjUsIm5iZiI6MTcyMjQyODc2NSwicGF0aCI6Ii81NzAyMzU0NS8zNTM4MDM2NDgtNzY4ZjNjMmItODNkMy00YTBhLTlkMTktNjNmZTUxYzFlYmEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEyMjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTQxMjVlOTI5ZWY3NGEyMTVkYTE1YjZjZDA0NmM4MTE0MGY0OGQ4MTcwODJhNWE0YzU3YmE2MDMyM2Y3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ay0RMndA-9sjRvic4--28phXqHANqDfZipBger2uRQQ)
> 
> 我之前用的是这个版本，这个版本可以解锁硬解但是不支持这个插件要是能适配太好了，正版有点望尘莫及

docker的话也是有开心版的

**Comment by sunxianhong** [comment]
> > > 我现在用的是[4.8.8.0] ， 有启动报错日志吗
> > 
> > ![Screenshot_20240731_185437.jpg](https://private-user-images.githubusercontent.com/57023545/353803648-768f3c2b-83d3-4a0a-9d19-63fe51c1eba0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjkwNjUsIm5iZiI6MTcyMjQyODc2NSwicGF0aCI6Ii81NzAyMzU0NS8zNTM4MDM2NDgtNzY4ZjNjMmItODNkMy00YTBhLTlkMTktNjNmZTUxYzFlYmEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEyMjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTQxMjVlOTI5ZWY3NGEyMTVkYTE1YjZjZDA0NmM4MTE0MGY0OGQ4MTcwODJhNWE0YzU3YmE2MDMyM2Y3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ay0RMndA-9sjRvic4--28phXqHANqDfZipBger2uRQQ)
> > 
> > 我之前用的是这个版本，这个版本可以解锁硬解但是不支持这个插件要是能适配太好了，正版有点望尘莫及
> 
> docker的话也是有开心版的

对这个就是那个开心版

**Comment by fengymi** [comment]
> > > > 我现在用的是[4.8.8.0] ， 有启动报错日志吗
> > > 
> > > 
> > > ![Screenshot_20240731_185437.jpg](https://private-user-images.githubusercontent.com/57023545/353803648-768f3c2b-83d3-4a0a-9d19-63fe51c1eba0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjkwNjUsIm5iZiI6MTcyMjQyODc2NSwicGF0aCI6Ii81NzAyMzU0NS8zNTM4MDM2NDgtNzY4ZjNjMmItODNkMy00YTBhLTlkMTktNjNmZTUxYzFlYmEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEyMjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTQxMjVlOTI5ZWY3NGEyMTVkYTE1YjZjZDA0NmM4MTE0MGY0OGQ4MTcwODJhNWE0YzU3YmE2MDMyM2Y3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ay0RMndA-9sjRvic4--28phXqHANqDfZipBger2uRQQ)
> > > 我之前用的是这个版本，这个版本可以解锁硬解但是不支持这个插件要是能适配太好了，正版有点望尘莫及
> > 
> > 
> > docker的话也是有开心版的
> 
> 对这个就是那个开心版

我的意思有4.8.8的开心版，也是解锁硬解的

**Comment by sunxianhong** [comment]
> > > > > 我现在用的是[4.8.8.0] ， 有启动报错日志吗
> > > > 
> > > > 
> > > > ![Screenshot_20240731_185437.jpg](https://private-user-images.githubusercontent.com/57023545/353803648-768f3c2b-83d3-4a0a-9d19-63fe51c1eba0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjkwNjUsIm5iZiI6MTcyMjQyODc2NSwicGF0aCI6Ii81NzAyMzU0NS8zNTM4MDM2NDgtNzY4ZjNjMmItODNkMy00YTBhLTlkMTktNjNmZTUxYzFlYmEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEyMjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTQxMjVlOTI5ZWY3NGEyMTVkYTE1YjZjZDA0NmM4MTE0MGY0OGQ4MTcwODJhNWE0YzU3YmE2MDMyM2Y3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ay0RMndA-9sjRvic4--28phXqHANqDfZipBger2uRQQ)
> > > > 我之前用的是这个版本，这个版本可以解锁硬解但是不支持这个插件要是能适配太好了，正版有点望尘莫及
> > > 
> > > 
> > > docker的话也是有开心版的
> > 
> > 对这个就是那个开心版
> 
> 我的意思有4.8.8的开心版，也是解锁硬解的

啊真的吗容器名字是啥

**Comment by fengymi** [comment]
> > > > > > 我现在用的是[4.8.8.0] ， 有启动报错日志吗
> > > > > 
> > > > > 
> > > > > ![Screenshot_20240731_185437.jpg](https://private-user-images.githubusercontent.com/57023545/353803648-768f3c2b-83d3-4a0a-9d19-63fe51c1eba0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjkwNjUsIm5iZiI6MTcyMjQyODc2NSwicGF0aCI6Ii81NzAyMzU0NS8zNTM4MDM2NDgtNzY4ZjNjMmItODNkMy00YTBhLTlkMTktNjNmZTUxYzFlYmEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEyMjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTQxMjVlOTI5ZWY3NGEyMTVkYTE1YjZjZDA0NmM4MTE0MGY0OGQ4MTcwODJhNWE0YzU3YmE2MDMyM2Y3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ay0RMndA-9sjRvic4--28phXqHANqDfZipBger2uRQQ)
> > > > > 我之前用的是这个版本，这个版本可以解锁硬解但是不支持这个插件要是能适配太好了，正版有点望尘莫及
> > > > 
> > > > 
> > > > docker的话也是有开心版的
> > > 
> > > 
> > > 对这个就是那个开心版
> > 
> > 
> > 我的意思有4.8.8的开心版，也是解锁硬解的
> 
> 啊真的吗容器名字是啥

直接docker hub上搜下，就前面几个

**Comment by sunxianhong** [comment]
![11](https://github.com/user-attachments/assets/7a8bdf51-e3c5-492f-9833-8ca2ebff890b)
![22](https://github.com/user-attachments/assets/2d870d57-05a5-404e-8906-1966c4c47ac7)
感谢找到能硬解的4.8.8了，有俩小问题embyTV版在手机上装能播放4K，在芝杜盒子上锁定1080P不到为啥电视是4K的。白夜追凶这个不能自动下弹幕，手动点搜索就会卡死只能关掉软件

**Comment by fengymi** [comment]
> ![11](https://private-user-images.githubusercontent.com/57023545/354038257-7a8bdf51-e3c5-492f-9833-8ca2ebff890b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0Nzc1ODMsIm5iZiI6MTcyMjQ3NzI4MywicGF0aCI6Ii81NzAyMzU0NS8zNTQwMzgyNTctN2E4YmRmNTEtZTNjNS00OTJmLTk4MzMtOGNhMmViZmY4OTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAxNTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMzNiNTdmNjVhNjA0MjcyYmRmZmNjNDkyYjBlNzk4M2JlOTEwMWY4ODRjOTZkZGQwOTI5ZDAxNGZhNmVlOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1D91HRzDrw_Rc5CsR7t5ndCfwsIolVpuDigmNSJgiwU) ![22](https://private-user-images.githubusercontent.com/57023545/354038262-2d870d57-05a5-404e-8906-1966c4c47ac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0Nzc1ODMsIm5iZiI6MTcyMjQ3NzI4MywicGF0aCI6Ii81NzAyMzU0NS8zNTQwMzgyNjItMmQ4NzBkNTctMDVhNS00MDRlLTg5MDYtMTk2NmM0YzQ3YWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAxNTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTI0NTlmMjA1YjdkYjM5ZWI0YjZlMmVlMjZjNDk4N2NkYjM5ODEwNWQ4M2FhY2MzOTliMDM2ZjQzMjRiZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5lqID5o627nEi2y9ephg6hpumoFzTsiBMYXqYtlpQqY) 感谢找到能硬解的4.8.8了，有俩小问题embyTV版在手机上装能播放4K，在芝杜盒子上锁定1080P不到为啥电视是4K的。白夜追凶这个不能自动下弹幕，手动点搜索就会卡死只能关掉软件

1. 你用的是什么版本的app
2. 你可以用页面试试手动搜索，数据是存在服务端的，app有可能因为查询网络时间太久显示卡死状态

**Comment by sunxianhong** [comment]
> > ![11](https://private-user-images.githubusercontent.com/57023545/354038257-7a8bdf51-e3c5-492f-9833-8ca2ebff890b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0Nzc1ODMsIm5iZiI6MTcyMjQ3NzI4MywicGF0aCI6Ii81NzAyMzU0NS8zNTQwMzgyNTctN2E4YmRmNTEtZTNjNS00OTJmLTk4MzMtOGNhMmViZmY4OTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAxNTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMzNiNTdmNjVhNjA0MjcyYmRmZmNjNDkyYjBlNzk4M2JlOTEwMWY4ODRjOTZkZGQwOTI5ZDAxNGZhNmVlOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1D91HRzDrw_Rc5CsR7t5ndCfwsIolVpuDigmNSJgiwU) ![22](https://private-user-images.githubusercontent.com/57023545/354038262-2d870d57-05a5-404e-8906-1966c4c47ac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0Nzc1ODMsIm5iZiI6MTcyMjQ3NzI4MywicGF0aCI6Ii81NzAyMzU0NS8zNTQwMzgyNjItMmQ4NzBkNTctMDVhNS00MDRlLTg5MDYtMTk2NmM0YzQ3YWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAxNTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTI0NTlmMjA1YjdkYjM5ZWI0YjZlMmVlMjZjNDk4N2NkYjM5ODEwNWQ4M2FhY2MzOTliMDM2ZjQzMjRiZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5lqID5o627nEi2y9ephg6hpumoFzTsiBMYXqYtlpQqY) 感谢找到能硬解的4.8.8了，有俩小问题embyTV版在手机上装能播放4K，在芝杜盒子上锁定1080P不到为啥电视是4K的。白夜追凶这个不能自动下弹幕，手动点搜索就会卡死只能关掉软件
> 
> 1. 你用的是什么版本的app
> 2. 你可以用页面试试手动搜索，数据是存在服务端的，app有可能因为查询网络时间太久显示卡死状态

![mmexport1722477856531.png](https://github.com/user-attachments/assets/2dc97464-4667-4f2a-8c7e-5a613a34a75c)

app是你发的那个tv版本,这是页面端下载时候的显示
