### ISSUE TITLE
使用fileball播放没有字幕

### ISSUE THREAD

**Issue by Cxquang** [fengymi/emby-plugin-danmu#8]
大佬，我使用fileball连接emby播放电影时没有字幕，该电影目录下已经有xml的弹幕文件了，这个是需要开启高级功能吗

**Comment by fengymi** [comment]
> 大佬，我使用fileball连接emby播放电影时没有字幕，该电影目录下已经有xml的弹幕文件了，这个是需要开启高级功能吗

没用过这个，你问问jellyfin那边怎么设置的。

**Comment by edhnt455** [comment]
> 大佬，我使用fileball连接emby播放电影时没有字幕，该电影目录下已经有xml的弹幕文件了，这个是需要开启高级功能吗

要开启实验室功能，有一个弹幕的，appletv端好像没有
