### ISSUE TITLE
重新下载弹幕

### ISSUE THREAD

**Issue by GuteNachte** [fengymi/emby-plugin-danmu#9]
ass弹幕设置文字大小还有弹幕速度等均无效后想着重新下载生成一遍，但是删除xml还有ass文件后点击计划任务就不下载弹幕了

**Comment by fengymi** [comment]
> ass弹幕设置文字大小还有弹幕速度等均无效后想着重新下载生成一遍，但是删除xml还有ass文件后点击计划任务就不下载弹幕了

/emby/api/danmu/{媒体id}?option=Refresh&X-Emby-Token=xxx
调接口手动刷新下

**Comment by GuteNachte** [comment]
ok
